Repository ucsb-cs156-s25/proj-dining-s25-10, pull requests merged in 2025-05, with the labels that each got.

#29 fixed latitude longitude bug
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
Labels: 5

#30 ac - added endpoint to retrieve individual review by id
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: Ready-For-Staff

#31 mh - added moderator role to backend, and included role in existing test for a mock user.
  docs/dokku.md
  src/main/java/edu/ucsb/cs156/dining/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/dining/entities/User.java
  src/main/java/edu/ucsb/cs156/dining/services/CurrentUserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/changes/Users.json
  src/test/java/edu/ucsb/cs156/dining/testconfig/MockCurrentUserServiceImpl.java
Labels: Ready-For-Staff

#34 Mz - post review page & also submit review button implementation
  frontend/src/App.js
  frontend/src/main/components/MenuItem/MenuItemTable.js
  frontend/src/main/components/MenuItemReviews/ReviewForm.js
  frontend/src/main/pages/MyReviews/MyReviewsIndexPage.js
  frontend/src/main/pages/ReviewsPage/CreateReviewsPage.js
  frontend/src/stories/pages/MenuItemReview/CreateReviewPage.stories.jsx
  frontend/src/stories/pages/MenuItemReview/CreateReviewPageWithID.stories.jsx
  frontend/src/tests/components/MenuItem/MenuItemTable.test.js
  frontend/src/tests/components/MenuItemReview/menuItemReview.test.js
  frontend/src/tests/components/Nav/Footer.test.js
  frontend/src/tests/pages/MenuItemReview/MenuItemReviewPageCreate.test.js
Labels: Ready-For-Staff, FINAL CHANCE

#38 Ben - Added GET endpoint for Individual Menu Item + Test
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsControllerTests.java
Labels: 10, Merge Candidate-CI

#35 Mz - auto approve reviews
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: 10, Merge Candidate-CI

#43 MZ - Fix: average score not recalculating on repeated item reviews
  frontend/src/fixtures/menuItemFixtures.js
  frontend/src/main/components/MenuItem/MenuItemTable.js
  frontend/src/tests/components/MenuItem/MenuItemTable.test.js
  frontend/src/tests/pages/MenuItem/MenuItemPage.test.js
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemRepository.java
  src/main/java/edu/ucsb/cs156/dining/repositories/ReviewRepository.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: 10, Merge Candidate-CI

#45 mh - moderators can now access the moderator page
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Moderate.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Moderate.test.js
Labels: 5, Ready-For-Staff, Merge Candidate-CI

#50 added test repetition for deployed tests that fail
  .github/workflows/04-gh-pages-redeploy-part-2.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/53-chromatic-main-branch.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
Labels: 10, Ready-For-Staff, Merge Candidate-CI
